name: xelis_mobile_wallet
description: XELIS Wallet
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  path: any
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  change_app_package_name: ^1.1.0
  cupertino_icons: ^1.0.6
  ffi: ^2.1.2
  flex_color_scheme: ^7.3.1
  flutter_form_builder: ^9.2.1
  flutter_riverpod: ^2.5.1
  form_builder_validators: ^9.1.0
  freezed_annotation: ^2.4.1
  go_router: ^13.2.2
  google_fonts: ^6.2.1
  intl: any
  jovial_svg: ^1.1.20
  json_annotation: ^4.8.1
  logging: ^1.2.0
  path_provider: ^2.1.2
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.2
  xelis_dart_sdk: ^0.16.2
  dots_indicator: ^3.0.0
  flutter_animate: ^4.5.0
  #  flutter_hooks: ^0.20.5
  #  hooks_riverpod: ^2.4.10
  loader_overlay: ^4.0.0
  random_avatar: ^0.0.8
  pretty_qr_code: ^3.3.0
  uuid: ^4.3.3
  flutter_native_splash: ^2.4.0
  window_manager: ^0.3.8
  flutter_launcher_icons: ^0.13.1

  flutter_rust_bridge: 2.0.0-dev.29
  rust_builder:
    path: rust_builder
  country_flags: ^2.2.0
  auto_size_text: ^3.0.0


dev_dependencies:
  build_runner: ^2.4.9
  go_router_builder: ^2.4.1
  ffigen: ^11.0.0
  flutter_lints: ^3.0.2
  #  flutter_test:
  #    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
#  integration_test:
#    sdk: flutter


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/banners/svg/
    - assets/icons/png/
    - assets/bg_dots.png


flutter_launcher_icons:
  image_path_android: "assets/icons/png/circle/black_background_green_logo.png"
  image_path_ios: "assets/icons/png/circle/black_background_green_logo.png"
  android: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  ios: true
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  windows:
    generate: true
    image_path: "assets/icons/png/circle/black_background_green_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/png/circle/black_background_green_logo.png"