name: genesix
description: Multiplatform mobile wallet for the XELIS network.
publish_to: 'none'

version: 0.0.3

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  path: any
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  change_app_package_name: ^1.1.0
  cupertino_icons: ^1.0.8
  ffi: ^2.1.2
  flutter_form_builder: ^9.2.1
  flutter_riverpod: ^2.5.1
  form_builder_validators: ^9.1.0
  freezed_annotation: ^2.4.1
  go_router: ^14.0.2
  google_fonts: ^6.2.1
  intl: any
#  jovial_svg: ^1.1.20
  json_annotation: ^4.9.0
  logging: ^1.2.0
  path_provider: ^2.1.3
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  xelis_dart_sdk: ^0.18.0
  #  flutter_animate: ^4.5.0
  #  flutter_hooks: ^0.20.5
  #  hooks_riverpod: ^2.4.10
  loader_overlay: ^4.0.0
  random_avatar: ^0.0.8
  pretty_qr_code: ^3.3.0
  flutter_native_splash: ^2.4.0
  window_manager: ^0.3.8
  country_flags: ^2.2.0
  auto_size_text: ^3.0.0
  package_info_plus: ^8.0.0
  file_picker: ^8.0.3
  icons_launcher: ^2.1.7
  url_launcher: ^6.2.6

  flutter_rust_bridge: 2.0.0-dev.33
  rust_builder:
    path: rust_builder

dev_dependencies:
  build_runner: ^2.4.9
  go_router_builder: ^2.6.2
  ffigen: ^11.0.0
  flutter_lints: ^3.0.2
  #  flutter_test:
  #    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  msix: ^3.16.7
#  integration_test:
#    sdk: flutter


flutter:
  generate: true
  uses-material-design: true

  assets:
#    - assets/banners/svg/
#    - assets/icons/png/
    - assets/bg_dots.png
