name: xelis_mobile_wallet
description: Xelis Mobile Wallet
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  change_app_package_name: ^1.1.0
  cryptography: ^2.7.0
  cryptography_flutter: ^2.3.2
  cupertino_icons: ^1.0.6
  ffi: ^2.1.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  flutter_rust_bridge: ^1.82.5
  flutter_secure_storage: ^9.0.0
  form_builder_validators: ^9.1.0
  freezed_annotation: ^2.4.1
  go_router: ^12.1.3
  google_fonts: ^6.1.0
  intl: any
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  jovial_svg: ^1.1.19
  json_annotation: ^4.8.1
  loading_animation_widget: ^1.2.0+4
  logging: ^1.2.0
  path_provider: ^2.1.1
  riverpod_annotation: ^2.3.3
  shared_preferences: ^2.2.2
  xelis_dart_sdk: ^0.12.1


dev_dependencies:
  build_runner: ^2.4.7
  go_router_builder: ^2.4.0
  ffigen: ^8.0.2
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  isar_generator: ^3.1.0+1
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.1


flutter:
  generate: true
  uses-material-design: true
