name: xelis_wallet_app
description: Xelis Wallet Mobile App
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.2.0
  flutter_rust_bridge: ^1.64.0
  go_router: ^6.0.9
  google_fonts: ^4.0.3
  logging: ^1.1.1
  riverpod_annotation: ^1.2.1


dev_dependencies:
  build_runner:
  custom_lint:
  ffigen: ^7.2.6
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  riverpod_generator: ^1.2.0
  riverpod_lint:


flutter:
  uses-material-design: true

  assets:
    - assets/xelis_logo_pastille_01.png
    - assets/xelis_logo_horizontal_color.png