name: xelis_mobile_wallet
description: Xelis Mobile Wallet
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.8.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.0
  flutter_rust_bridge: ^1.67.0
  form_builder_validators: ^8.5.0
  freezed_annotation: ^2.2.0
  go_router: ^6.2.0
  google_fonts: ^4.0.3
  intl: any
  json_annotation: ^4.8.0
  logging: ^1.1.1
  riverpod_annotation: ^2.0.0
  shared_preferences: ^2.0.18


dev_dependencies:
  build_runner: ^2.3.3
  custom_lint:
  ffigen: ^7.2.6
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  riverpod_generator: ^2.0.0
  riverpod_lint:


flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/xelis_logo_pastille_01.png
    - assets/xelis_logo_horizontal_color.png